name: Appetize Live Preview

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile_app

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Create dummy .env file
        run: touch .env

      - name: Build Android Debug APK
        run: flutter build apk --debug

      - name: Upload to Appetize
        uses: appetizeio/github-action-appetize@v1.0.5
        with:
          apiToken: ${{ secrets.APPETIZE_API_TOKEN }}
          appFile: mobile_app/build/app/outputs/flutter-apk/app-debug.apk
          platform: 'android'
